[extension]
name = "voplay"
include = [
  "js/dist",
]

[extension.native]
path = "rust/target/{profile}/libvo_voplay"

[[extension.native.targets]]
target = "aarch64-apple-darwin"
library = "libvo_voplay.dylib"

[[extension.native.targets]]
target = "x86_64-unknown-linux-gnu"
library = "libvo_voplay.so"

[extension.wasm]
type = "bindgen"
wasm = "voplay_island_bg.wasm"
js_glue = "voplay_island.js"
local_wasm = "rust/pkg-island/voplay_island_bg.wasm"
local_js_glue = "rust/pkg-island/voplay_island.js"

[extension.web]
entry = "Run"
capabilities = ["widget", "island_transport", "vo_web", "vfs"]

[extension.web.js]
renderer = "js/dist/voplay-render-island.js"
