[extension]
name = "voplay"
path = "rust/target/{profile}/libvo_voplay"
include = [
  "js/dist",
]

[extension.wasm]
type = "bindgen"
wasm = "voplay_island_bg.wasm"
js_glue = "voplay_island.js"

[studio]
entry = "Run"
capabilities = ["widget", "island_transport", "vo_web", "vfs"]
renderer = "js/dist/voplay-render-island.js"
