use super::pass_dispatch::{FramePassDispatcher, RenderPassResources};
use super::*;
use crate::draw_list::Frame2D;

pub(super) struct FramePassSequenceContext<'a> {
    pub(super) frame_graph: &'a mut FrameGraph,
    pub(super) encoder: Option<wgpu::CommandEncoder>,
    pub(super) output: Option<wgpu::SurfaceTexture>,
    pub(super) surface_view: &'a wgpu::TextureView,
    pub(super) frame: &'a Frame2D,
    pub(super) camera_alignment: u32,
    pub(super) clear_color: wgpu::Color,
    pub(super) camera3d_uniform: Option<&'a Camera3DUniform>,
    pub(super) camera3d_state: Option<(Vec3, Vec3, Vec3, f32, f32, f32)>,
    pub(super) skybox_cubemap_id: Option<u32>,
    pub(super) light_uniform: &'a mut LightUniform,
    pub(super) planned_model_draws: &'a [ModelDraw],
    pub(super) primitive_depth_draws: &'a mut Vec<PrimitiveDraw>,
    pub(super) primitive_depth_chunks: &'a [PrimitiveChunkRef],
    pub(super) primitive_shadow_draws: &'a mut Vec<PrimitiveDraw>,
    pub(super) primitive_shadow_chunks: &'a [PrimitiveChunkRef],
    pub(super) retained_scene_draws: &'a [u32],
    pub(super) planned_primitive_draws: &'a [PrimitiveDraw],
    pub(super) planned_primitive_chunks: &'a [PrimitiveChunkRef],
    pub(super) planned_water_draws: &'a [PrimitiveDraw],
    pub(super) planned_water_chunks: &'a [PrimitiveChunkRef],
    pub(super) projected_decal_atlas_bindings: &'a [ProjectedDecalAtlasBinding],
    pub(super) projected_decals: &'a [PostDecalGpu],
    pub(super) projected_decal_atlas_binding_count: u32,
    pub(super) shadow_resolution: u32,
    pub(super) shadow_quality: u32,
    pub(super) shadow_distance: f32,
    pub(super) shadow_fade: f32,
    pub(super) shadow_softness: f32,
    pub(super) shadow_strength: f32,
    pub(super) post_depth_active: bool,
    pub(super) aspect: f32,
    pub(super) perf_enabled: bool,
    pub(super) perf: &'a mut RendererPerfStats,
    pub(super) primitive_depth_draw_calls: &'a mut u32,
    pub(super) primitive_shadow_draw_calls: &'a mut u32,
    pub(super) primitive_main_stats: &'a mut PrimitiveDrawStats,
    pub(super) primitive_transparent_stats: &'a mut PrimitiveDrawStats,
    pub(super) primitive_main_submitted: &'a mut bool,
    pub(super) primitive_water_stats: &'a mut PrimitiveDrawStats,
    pub(super) bloom_threshold: f32,
    pub(super) bloom_strength: f32,
    pub(super) sharpen_strength: f32,
    pub(super) fxaa_strength: f32,
    pub(super) contact_ao_strength: f32,
    pub(super) contact_ao_radius: f32,
    pub(super) contact_ao_depth_scale: f32,
    pub(super) contact_ao_detail_strength: f32,
    pub(super) contact_ao_detail_radius: f32,
    pub(super) contact_ao_normal_bias: f32,
    pub(super) contact_ao_quality: u32,
}

pub(super) struct FramePassSequenceTimings {
    pub(super) depth_pass_ms: f64,
    pub(super) shadow_pass_ms: f64,
    pub(super) main_pass_ms: f64,
    pub(super) water_pass_ms: f64,
    pub(super) post_pass_ms: f64,
    pub(super) overlay_pass_ms: f64,
    pub(super) shadow_active: bool,
}

impl Renderer {
    pub(super) fn execute_frame_pass_sequence(
        &mut self,
        context: FramePassSequenceContext<'_>,
    ) -> Result<FramePassSequenceTimings, String> {
        let mut shadow_active = false;
        let mut dispatcher = FramePassDispatcher {
            resources: RenderPassResources {
                device: &self.device,
                queue: &self.queue,
                surface_config: &self.surface_config,
                targets: &self.resources,
                post_uniform_buffer: &self.post_uniform_buffer,
                post_decal_uniform_buffer: &self.post_decal_uniform_buffer,
                post_bind_group: &self.post_bind_group,
                camera_bind_group: &self.camera_bind_group,
                pipeline2d: &mut self.pipeline2d,
                pipeline_sprite: &mut self.pipeline_sprite,
                pipeline3d: &mut self.pipeline3d,
                primitive_pipeline: &mut self.primitive_pipeline,
                pipeline_depth: &mut self.pipeline_depth,
                pipeline_shadow: &mut self.pipeline_shadow,
                pipeline_skybox: &mut self.pipeline_skybox,
                pipeline_post: &self.pipeline_post,
                model_manager: &self.model_manager,
                texture_manager: &self.texture_manager,
                render_world: &self.render_world,
            },
            encoder: context.encoder,
            output: context.output,
            surface_view: context.surface_view,
            frame: context.frame,
            camera_alignment: context.camera_alignment,
            clear_color: context.clear_color,
            camera3d_uniform: context.camera3d_uniform,
            camera3d_state: context.camera3d_state,
            skybox_cubemap_id: context.skybox_cubemap_id,
            light_uniform: context.light_uniform,
            planned_model_draws: context.planned_model_draws,
            primitive_depth_draws: context.primitive_depth_draws,
            primitive_depth_chunks: context.primitive_depth_chunks,
            primitive_shadow_draws: context.primitive_shadow_draws,
            primitive_shadow_chunks: context.primitive_shadow_chunks,
            retained_scene_draws: context.retained_scene_draws,
            planned_primitive_draws: context.planned_primitive_draws,
            planned_primitive_chunks: context.planned_primitive_chunks,
            planned_water_draws: context.planned_water_draws,
            planned_water_chunks: context.planned_water_chunks,
            projected_decal_atlas_bindings: context.projected_decal_atlas_bindings,
            projected_decals: context.projected_decals,
            projected_decal_atlas_binding_count: context.projected_decal_atlas_binding_count,
            shadow_resolution: context.shadow_resolution,
            shadow_quality: context.shadow_quality,
            shadow_distance: context.shadow_distance,
            shadow_fade: context.shadow_fade,
            shadow_softness: context.shadow_softness,
            shadow_strength: context.shadow_strength,
            main_aux_targets_enabled: context.post_depth_active,
            aspect: context.aspect,
            perf_enabled: context.perf_enabled,
            perf: context.perf,
            primitive_depth_draw_calls: context.primitive_depth_draw_calls,
            primitive_shadow_draw_calls: context.primitive_shadow_draw_calls,
            primitive_main_stats: context.primitive_main_stats,
            primitive_transparent_stats: context.primitive_transparent_stats,
            primitive_main_submitted: context.primitive_main_submitted,
            primitive_water_stats: context.primitive_water_stats,
            shadow_active: &mut shadow_active,
            post_uniforms_uploaded: false,
            bloom_threshold: context.bloom_threshold,
            bloom_strength: context.bloom_strength,
            sharpen_strength: context.sharpen_strength,
            fxaa_strength: context.fxaa_strength,
            contact_ao_strength: context.contact_ao_strength,
            contact_ao_radius: context.contact_ao_radius,
            contact_ao_depth_scale: context.contact_ao_depth_scale,
            contact_ao_detail_strength: context.contact_ao_detail_strength,
            contact_ao_detail_radius: context.contact_ao_detail_radius,
            contact_ao_normal_bias: context.contact_ao_normal_bias,
            contact_ao_quality: context.contact_ao_quality,
        };
        let diagnostics = context
            .frame_graph
            .executor()
            .execute_all(&mut dispatcher)?;
        let elapsed = |kind| {
            diagnostics
                .iter()
                .find(|diagnostic| diagnostic.kind == kind)
                .map(|diagnostic| diagnostic.elapsed_ms)
                .unwrap_or(0.0)
        };
        Ok(FramePassSequenceTimings {
            depth_pass_ms: elapsed(RenderPassKind::DepthPrepass),
            shadow_pass_ms: elapsed(RenderPassKind::Shadow),
            main_pass_ms: elapsed(RenderPassKind::MainOpaque),
            water_pass_ms: elapsed(RenderPassKind::Water),
            post_pass_ms: elapsed(RenderPassKind::Post),
            overlay_pass_ms: elapsed(RenderPassKind::Overlay),
            shadow_active,
        })
    }
}
